/* ============================================================
   データ: アイテム（素材・完成品・消費アイテム・アーティファクト）
   ============================================================ */

/* ── アイテム日本語名 ── */
/* ── 素材アイテム ── */
const ITEMS=[
  {id:'bfsword', name:'B.F.ソード', jaName: 'B.F.ソード', icon:'⚔️', type:'comp', imgId: 1}, 
  {id:'recurverecurvebow', name:'Recurve recurvebow', jaName: 'リカーブボウ', icon:'🏹', type:'comp', imgId: 2},
  {id:'needlesslylargerod', name:'Needlessly Large needlesslylargerod', jaName: 'ムダニデカイロッド', icon:'🔮', type:'comp', imgId: 3}, 
  {id:'tearofthegoddess', name:'tearofthegoddess of the Goddess', jaName: '女神の涙', icon:'💧', type:'comp', imgId: 4},
  {id:'chainvest', name:'chainvest Vest', jaName: 'チェインベスト', icon:'🛡️', type:'comp', imgId: 5}, 
  {id:'negatroncloak', name:'Negatron negatroncloak', jaName: 'ネガトロンクローク', icon:'🧥', type:'comp', imgId: 6},
  {id:'giantbelt', name:"Giant's giantbelt", jaName: 'ジャイアントベルト', icon:'💖', type:'comp', imgId: 7}, 
  {id:'sparringgloves', name:'Sparring sparringglovess', jaName: 'スパーリンググローブ', icon:'🥊', type:'comp', imgId: 9},
  {id:'spatula', name:'Spatula', jaName: '黄金のへら', icon:'🍳', type:'comp', imgId: 8},
  {id:'fryingpan', name:'Frying fryingpan', jaName: 'フライパン', icon:'🥘', type:'comp', imgId: 10}
];

/* ── サイオニック専用アイテム ── */
const PSIONIC_ITEMS = [
  { name: 'tft17_item_psyops_targetlockmod', jaName: 'ターゲットロック スコープ' },
  { name: 'tft17_item_psyops_sympatheticimplantmod', jaName: '共感インプラント' },
  { name: 'tft17_item_psyops_dronemod', jaName: 'ドローン アップリンク' },
  { name: 'tft17_item_psyops_chemicalcapacitormod', jaName: 'マルウェア マトリックス' },
  { name: 'tft17_item_psyops_grenademod', jaName: 'バイオ物質保存装置' }
];

/* ── 完成アイテムのレシピ ── */
const ITEM_RECIPES = {
  'bfsword_bfsword':{id:'deathblade', name:'deathblade', jaName: 'デスブレード', icon:'🗡️', imgId: 11}, 
  'bfsword_recurvebow':{id:'giantslayer', name:'Giant Slayer', jaName: 'ジャイアントスレイヤー', icon:'🪚', imgId: 12},
  'bfsword_needlesslylargerod':{id:'gunblade', name:'Hextech Gunblade', jaName: 'ヘクステックガンブレード', icon:'🔫', imgId: 13}, 
  'bfsword_tearofthegoddess':{id:'shojin', name:'spearofshojin', jaName: 'ショウジンの矛', icon:'🔱', imgId: 14},
  'bfsword_chainvest':{id:'edgeofnight', name:'guardianangel', jaName: 'ナイトエッジ', icon:'🌑', imgId: 15}, 
  'bfsword_negatroncloak':{id:'bloodthirster', name:'Bloodthirster', jaName: 'ブラッドサースター', icon:'🧛', imgId: 16},
  'bfsword_giantbelt':{id:'steraksgage', name:"steraksgage", jaName: 'ステラックの篭手', icon:'💪', imgId: 17}, 
  'bfsword_sparringgloves':{id:'infinityedge', name:'Infinity Edge', jaName: 'インフィニティエッジ', icon:'✨', imgId: 19},
  'recurvebow_recurvebow':{id:'rapidfirecannon', name:'rapidfirecannon', jaName: 'レッドバフ', icon:'🔥', imgId: 22}, 
  'recurvebow_needlesslylargerod':{id:'guinsoo', name:"Guinsoo's Rageblade", jaName: 'グインソー レイジブレード', icon:'☄️', imgId: 23},
  'recurvebow_tearofthegoddess':{id:'statikk', name:'statikkshiv', jaName: 'ヴォイドスタッフ', icon:'⚡', imgId: 24}, 
  'recurvebow_chainvest':{id:'titans', name:"Titan's Resolve", jaName: '巨人の誓い', icon:'🗿', imgId: 25},
  'recurvebow_negatroncloak':{id:'runaan', name:"runaanshurricane", jaName: 'クラーケンの怒り', icon:'🌪️', imgId: 26}, 
  'recurvebow_giantbelt':{id:'nashor', name:"leviathan", jaName: 'ナッシャー トゥース', icon:'🦷', imgId: 27},
  'recurvebow_sparringgloves':{id:'lastwhisper', name:'Last Whisper', jaName: 'ラストウィスパー', icon:'🏹', imgId: 29},
  'needlesslylargerod_needlesslylargerod':{id:'rabadon', name:"Rabadon's Deathcap", jaName: 'ラバドンデスキャップ', icon:'🎩', imgId: 33}, 
  'needlesslylargerod_tearofthegoddess':{id:'archangel', name:"Archangel's Staff", jaName: 'アークエンジェルスタッフ', icon:'👼', imgId: 34},
  'needlesslylargerod_chainvest':{id:'crownguard', name:'Crownguard', jaName: 'クラウンガード', icon:'👑', imgId: 35}, 
  'needlesslylargerod_negatroncloak':{id:'ionic', name:'Ionic Spark', jaName: 'アイオニックスパーク', icon:'🌩️', imgId: 36},
  'needlesslylargerod_giantbelt':{id:'morello', name:'Morellonomicon', jaName: 'モレロノミコン', icon:'📜', imgId: 37}, 
  'needlesslylargerod_sparringgloves':{id:'jeweled', name:'Jeweled Gauntlet', jaName: 'ジュエル ガントレット', icon:'💎', imgId: 39},
  'tearofthegoddess_tearofthegoddess':{id:'bluebuff', name:'Blue Buff', jaName: 'ブルーバフ', icon:'🟦', imgId: 44}, 
  'tearofthegoddess_chainvest':{id:'vow', name:"frozenheart", jaName: 'プロテクターの誓い', icon:'🤝', imgId: 45},
  'tearofthegoddess_negatroncloak':{id:'adaptive', name:'Adaptive Helm', jaName: 'アダプティブヘルム', icon:'🪖', imgId: 46}, 
  'tearofthegoddess_giantbelt':{id:'redemption', name:'Redemption', jaName: 'スピリット ビサージュ', icon:'😇', imgId: 47},
  'tearofthegoddess_sparringgloves':{id:'hoj', name:'unstableconcoction', jaName: 'ハンド オブ ジャスティス', icon:'⚖️', imgId: 49},
  'chainvest_chainvest':{id:'bramble', name:'Bramble Vest', jaName: 'ブランブルベスト', icon:'🌵', imgId: 55}, 
  'chainvest_negatroncloak':{id:'gargoyle', name:'Gargoyle Stoneplate', jaName: 'ガーゴイルストーンプレート', icon:'🗿', imgId: 56},
  'chainvest_giantbelt':{id:'sunfire', name:'redbuff', jaName: 'サンファイアケープ', icon:'☀️', imgId: 57}, 
  'chainvest_sparringgloves':{id:'steadfast', name:'nightharvester', jaName: '揺るがぬ心', icon:'❤️', imgId: 59},
  'negatroncloak_negatroncloak':{id:'dragon', name:"Dragon's Claw", jaName: 'ドラゴン クロウ', icon:'🐉', imgId: 66}, 
  'negatroncloak_giantbelt':{id:'evenshroud', name:'spectralgauntlet', jaName: 'イーブンシュラウド', icon:'🦇', imgId: 67},
  'negatroncloak_sparringgloves':{id:'quicksilver', name:'Quicksilver', jaName: 'クイックシルバー', icon:'🧣', imgId: 69}, 
  'giantbelt_giantbelt':{id:'warmog', name:"Warmog's Armor", jaName: 'ワーモグ アーマー', icon:'🌿', imgId: 77}, 
  'giantbelt_sparringgloves':{id:'guardbreaker', name:'powergauntlet', jaName: 'ストライカー フレイル', icon:'🔨', imgId: 79}, 
  'sparringgloves_sparringgloves':{id:'thiefs', name:"Thief's sparringglovess", jaName: '盗賊のグローブ', icon:'🧤', imgId: 99},
  'spatula_bf':{id:'emblem_darkstar', name:'Dark Star Emblem', jaName: 'ダークスターの紋章', icon:'🛡️', imgId: 81, grantedTrait: 'Dark Star'}, 
  'spatula_recurvebow':{id:'emblem_timebreaker', name:'pulsefire Emblem', jaName: 'タイムブレイカーの紋章', icon:'🏹', imgId: 82, grantedTrait: 'Timebreaker'},
  'spatula_needlesslylargerod':{id:'emblem_stargazer', name:'Stargazer Emblem', jaName: '星の観測者の紋章', icon:'🔮', imgId: 83, grantedTrait: 'Stargazer'}, 
  'spatula_tearofthegoddess':{id:'emblem_spacegroove', name:'SpaceGroove Emblem', jaName: 'スペースグルーヴの紋章', icon:'💧', imgId: 84, grantedTrait: 'Space Groove'},
  'spatula_chainvest':{id:'emblem_meeple', name:'astronaut Emblem', jaName: 'ミィプルの紋章', icon:'🛡️', imgId: 85, grantedTrait: 'Meeple'}, 
  'spatula_negatroncloak':{id:'emblem_arbiter', name:'favored Emblem', jaName: 'アービターの紋章', icon:'🧥', imgId: 86, grantedTrait: 'Arbiter'},
  'spatula_giantbelt':{id:'emblem_primordian', name:'Primordian Emblem', jaName: 'プリモーディアンの紋章', icon:'💖', imgId: 87, grantedTrait: 'Primordian'}, 
  'spatula_sparringgloves':{id:'emblem_nova', name:'drx Emblem', jaName: 'N.O.V.A.の紋章', icon:'🥊', imgId: 89, grantedTrait: 'N.O.V.A.'},
  'spatula_spatula':{id:'tacticians_crown', name:"forceofnature", jaName: 'タクティシャンの王冠', icon:'👑', imgId: 88, teamSizeBonus: 1},
  'fryingpan_bf':{id:'emblem_marauder', name:'meleetrait Emblem', jaName: '略奪者の紋章', icon:'🛡️', imgId: 91, grantedTrait: 'Marauder'},
  'fryingpan_recurvebow':{id:'emblem_challenger', name:'astrait Emblem', jaName: 'チャレンジャーの紋章', icon:'🏹', imgId: 92, grantedTrait: 'Challenger'},
  'fryingpan_needlesslylargerod':{id:'emblem_voyager', name:'flextrait Emblem', jaName: 'ボイジャーの紋章', icon:'🔮', imgId: 93, grantedTrait: 'Voyager'},
  'fryingpan_tearofthegoddess':{id:'emblem_shepherd', name:'summontrait Emblem', jaName: '導き手の紋章', icon:'💧', imgId: 94, grantedTrait: 'Shepherd'},
  'fryingpan_chainvest':{id:'emblem_bastion', name:'resisttank Emblem', jaName: 'バスティオンの紋章', icon:'🛡️', imgId: 95, grantedTrait: 'Bastion'},
  'fryingpan_negatroncloak':{id:'emblem_vanguard', name:'shieldtank Emblem', jaName: 'ヴァンガードの紋章', icon:'🧥', imgId: 96, grantedTrait: 'Vanguard'},
  'fryingpan_giantbelt':{id:'emblem_brawler', name:'hptank Emblem', jaName: 'ブローラーの紋章', icon:'💖', imgId: 97, grantedTrait: 'Brawler'},
  'fryingpan_sparringgloves':{id:'emblem_rogue', name:'assassintrait Emblem', jaName: 'ローグの紋章', icon:'🥊', imgId: 98, grantedTrait: 'Rogue'},
  'unbuildable_anima': {id:'emblem_anima', name:'animasquad Emblem', jaName: 'アニマの紋章', icon:'🛡️', imgId: 101, grantedTrait: 'Anima'},
  'unbuildable_psionic': {id:'emblem_psionic', name:'Psyops Emblem', jaName: 'サイオニックの紋章', icon:'🔮', imgId: 102, grantedTrait: 'Psionic'},
  'unbuildable_sniper': {id:'emblem_sniper', name:'rangedtrait Emblem', jaName: 'スナイパーの紋章', icon:'🏹', imgId: 103, grantedTrait: 'Sniper'}
};

/* ── 消費アイテム ── */
const CONSUMABLES = {
  TINY_DUPE: { id: 'tiny_dupe', name: 'Tiny Champion Duplicator', jaName: '小さなチャンピオン複製機', icon: '🔹', type:'consumable', imgId: 905 },
  LESSER_DUPE: { id: 'lesser_dupe', name: 'Lesser Champion Duplicator', jaName: '小型チャンピオン複製機', icon: '🔹', type:'consumable', imgId: 901 },
  CHAMP_DUPE: { id: 'champ_dupe', name: 'Champion Duplicator', jaName: 'チャンピオン複製機', icon: '🔸', type:'consumable', imgId: 902 },
  REFORGER: { id: 'reforger', name: 'Reforger', jaName: '再合成装置', icon: '🔨', type:'consumable', imgId: 903 },
  REMOVER: { id: 'remover', name: 'itemremover', jaName: '磁力式除去装置', icon: '🧲', type:'consumable', imgId: 904 }

};

/* ── アーティファクト ── */
const ARTIFACTS = [
  { id: 'ahris_aura', name: "Ahri's Aura", jaName: 'アーリのオーラ', type: 'artifact', imgName: 'tft17_item_artifact_ahriartifact' },
  { id: 'evelynns_intuition', name: "Evelynn's Intuition", jaName: 'イブリンの直感', type: 'artifact', imgName: 'tft17_item_artifact_evelynnartifact' },
  { id: 'trinityforce', name: 'Trinity Force', jaName: 'インフィニティ フォース', type: 'artifact', imgName: 'tft4_item_ornninfinityforce' },
  { id: 'varuss_tenacity', name: "Varus's Tenacity", jaName: 'ヴァルスの執念', type: 'artifact', imgName: 'tft17_item_artifact_varusartifact' },
  { id: 'witsend', name: "Wit's End", jaName: 'ウィッツ エンド', type: 'artifact', imgName: 'tft_item_artifact_witsend' },
  { id: 'voidgauntlet', name: 'Void Gauntlet', jaName: 'ヴォイド ガントレット', type: 'artifact', imgName: 'tft_item_artifact_voidgauntlet' },
  { id: 'ekkos_patience', name: "Ekko's Patience", jaName: 'エコーの忍耐', type: 'artifact', imgName: 'tft17_item_artifact_ekkoartifact' },
  { id: 'gamblersblade', name: "Gambler's Blade", jaName: 'ギャンブラーの剣', type: 'artifact', imgName: 'tft7_item_shimmerscalegamblersblade' },
  { id: 'goldcollector', name: 'The Collector', jaName: 'ゴールド コレクター', type: 'artifact', imgName: 'tft4_item_ornnthecollector' },
  { id: 'seekersarmguard', name: "Seeker's Armguard", jaName: 'シーカー アームガード', type: 'artifact', imgName: 'tft_item_artifact_seekersarmguard' },
  { id: 'silvermeredawn', name: 'Silvermere Dawn', jaName: 'シルバーミアの夜明け', type: 'artifact', imgName: 'tft_item_artifact_silvermeredawn' },
  { id: 'statikkshiv_artifact', name: 'Statikk Shiv Artifact', jaName: 'スタティック シヴ', type: 'artifact', imgName: 'tft_item_artifact_statikkshiv' },
  { id: 'snipersfocus', name: "Sniper's Focus", jaName: 'スナイパー フォーカス', type: 'artifact', imgName: 'tft9_item_ornnhorizonfocus' },
  { id: 'threshs_lantern', name: "Thresh's Lantern", jaName: 'スレッシュのランタン', type: 'artifact', imgName: 'tft17_item_artifact_threshlantern' },
  { id: 'zhonyasparadox', name: "Zhonya's Paradox", jaName: 'ゾーニャの砂時計', type: 'artifact', imgName: 'tft4_item_ornnzhonyasparadox' },
  { id: 'sorakas_miracle', name: "Soraka's Miracle", jaName: 'ソラカの奇跡', type: 'artifact', imgName: 'tft17_item_artifact_sorakaartifact' },
  { id: 'titanichydra', name: 'Titanic Hydra', jaName: 'タイタン ハイドラ', type: 'artifact', imgName: 'tft_item_artifact_titanichydra' },
  { id: 'deathsdefiance', name: "Death's Defiance", jaName: 'デス ディファイアンス', type: 'artifact', imgName: 'tft4_item_ornndeathsdefiance' },
  { id: 'dawncore', name: 'Dawncore', jaName: 'ドーンコア', type: 'artifact', imgName: 'tft_item_artifact_dawncore' },
  { id: 'hullcrusher', name: 'Hullcrusher', jaName: 'ハルクラッシャー', type: 'artifact', imgName: 'tft9_item_ornnhullbreaker' },
  { id: 'fishbones', name: 'Fishbones', jaName: 'フィッシュボーン', type: 'artifact', imgName: 'tft_item_artifact_fishbones' },
  { id: 'flickerblade', name: 'Flickerblade', jaName: 'フリッカーブレード', type: 'artifact', imgName: 'tft_item_artifact_navoriflickerblades' },
  { id: 'prowlersclaw', name: "Prowler's Claw", jaName: 'プローラー クロウ', type: 'artifact', imgName: 'tft_item_artifact_prowlersclaw' },
  { id: 'mittens', name: 'Mittens', jaName: 'ミトン', type: 'artifact', imgName: 'tft_item_artifact_mittens' },
  { id: 'mogulsmail', name: "Mogul's Mail", jaName: 'モーグル メイル', type: 'artifact', imgName: 'tft7_item_shimmerscalemogulsmail' },
  { id: 'yasuos_bladework', name: "Yasuo's Bladework", jaName: 'ヤスオのブレードワーク', type: 'artifact', imgName: 'tft17_item_artifact_yasuoartifact' },
  { id: 'lightshieldcrest', name: 'Lightshield Crest', jaName: 'ライトシールドのクレスト', type: 'artifact', imgName: 'tft_item_artifact_lightshieldcrest' },
  { id: 'rapidfirecannon_artifact', name: 'Rapid Firecannon Artifact', jaName: 'ラピッド ファイアキャノン', type: 'artifact', imgName: 'tft_item_artifact_rapidfirecannon' },
  { id: 'lichbane', name: 'Lich Bane', jaName: 'リッチ ベイン', type: 'artifact', imgName: 'tft_item_artifact_lichbane' },
  { id: 'ludenstempest', name: "Luden's Tempest", jaName: 'ルーデン テンペスト', type: 'artifact', imgName: 'tft_item_artifact_ludenstempest' },
  { id: 'unendingdespair', name: 'Unending Despair', jaName: '不屈', type: 'artifact', imgName: 'tft_item_artifact_unendingdespair' },
  { id: 'everlastingpact', name: 'Everlasting Pact', jaName: '不滅の協定', type: 'artifact', imgName: 'tft_item_artifact_eternalpact' },
  { id: 'dusksblessing', name: "Dusk's Blessing", jaName: '夕闇の加護', type: 'artifact', imgName: 'tft_item_artifact_aegisofdusk' },
  { id: 'dawnsblessing', name: "Dawn's Blessing", jaName: '夜明けの加護', type: 'artifact', imgName: 'tft_item_artifact_aegisofdawn' },
  { id: 'hatjuice', name: 'Hat Juice', jaName: '帽子ジュース', type: 'artifact', imgName: 'tft_item_artifact_cappajuice' },
  { id: 'blightingjewel', name: 'Blighting Jewel', jaName: '枯死の宝石', type: 'artifact', imgName: 'tft_item_artifact_blightingjewel' },
  { id: 'hellfirehatchet', name: 'Hellfire Hatchet', jaName: '獄炎のハチェット', type: 'artifact', imgName: 'tft_item_artifact_hellfirehatchet' },
  { id: 'talismanofascension', name: 'Talisman of Ascension', jaName: '超越のタリスマン', type: 'artifact', imgName: 'tft_item_artifact_talismanofascension' },
  { id: 'crown_of_demacia', name: 'Crown of Demacia', jaName: 'デマーシアの王冠', type: 'artifact', imgName: 'tft9_item_crownofdemacia' }
];

/* ── レディアントアイテム ── */
const RADIANT_ITEMS = [
  { id: 'r_deathblade', name: 'Luminous Deathblade', jaName: 'レディアント デスブレード', type: 'radiant', imgName: 'tft5_item_deathbladeradiant' },
  { id: 'r_giantslayer', name: 'Demonslayer', jaName: 'レディアント ジャイアントスレイヤー', type: 'radiant', imgName: 'tft5_item_giantslayerradiant' },
  { id: 'r_gunblade', name: 'Hextech Lifeblade', jaName: 'レディアント ヘクステックガンブレード', type: 'radiant', imgName: 'tft5_item_hextechgunbladeradiant' },
  { id: 'r_shojin', name: 'Spear of Hirana', jaName: 'レディアント ショウジンの矛', type: 'radiant', imgName: 'tft5_item_spearofshojinradiant' },
  { id: 'r_edgeofnight', name: 'Brink of Dawn', jaName: 'レディアント ナイトエッジ', type: 'radiant', imgName: 'tft5_item_guardianangelradiant' },
  { id: 'r_bloodthirster', name: 'Blessed Bloodthirster', jaName: 'レディアント ブラッドサースター', type: 'radiant', imgName: 'tft5_item_bloodthirsterradiant' },
  { id: 'r_steraksgage', name: "Sterak's Megashield", jaName: 'レディアント ステラックの篭手', type: 'radiant', imgName: 'tft5_item_steraksgageradiant' },
  { id: 'r_infinityedge', name: 'Zenith Edge', jaName: 'レディアント インフィニティエッジ', type: 'radiant', imgName: 'tft5_item_infinityedgeradiant' },
  { id: 'r_rapidfirecannon', name: 'Crest of Cinders', jaName: 'レディアント レッドバフ', type: 'radiant', imgName: 'tft5_item_rapidfirecannonradiant' }, 
  { id: 'r_guinsoo', name: "Guinsoo's Reckoning", jaName: 'レディアント グインソー レイジブレード', type: 'radiant', imgName: 'tft5_item_guinsoosragebladeradiant' },
  { id: 'r_statikk', name: "Statikk's Favor", jaName: 'レディアント ヴォイドスタッフ', type: 'radiant', imgName: 'tft5_item_statikkshivradiant' },
  { id: 'r_titans', name: "Titan's Vow", jaName: 'レディアント 巨人の誓い', type: 'radiant', imgName: 'tft5_item_titansresolveradiant' },
  { id: 'r_runaan', name: "Runaan's Tempest", jaName: 'レディアント クラーケンの怒り', type: 'radiant', imgName: 'tft5_item_runaanshurricaneradiant' },
  { id: 'r_nashor', name: "Baron's Gift", jaName: 'レディアント ナッシャー トゥース', type: 'radiant', imgName: 'tft5_item_leviathanradiant' },
  { id: 'r_lastwhisper', name: 'Eternal Whisper', jaName: 'レディアント ラストウィスパー', type: 'radiant', imgName: 'tft5_item_lastwhisperradiant' },
  { id: 'r_rabadon', name: "Rabadon's Ascended Deathcap", jaName: 'レディアント ラバドンデスキャップ', type: 'radiant', imgName: 'tft5_item_rabadonsdeathcapradiant' },
  { id: 'r_archangel', name: "Urf-Angel's Staff", jaName: 'レディアント アークエンジェルスタッフ', type: 'radiant', imgName: 'tft5_item_archangelsstaffradiant' },
  { id: 'r_crownguard', name: 'Royal Crownshield', jaName: 'レディアント クラウンガード', type: 'radiant', imgName: 'tft5_item_crownguardradiant' },
  { id: 'r_ionic', name: 'Covalent Spark', jaName: 'レディアント アイオニックスパーク', type: 'radiant', imgName: 'tft5_item_ionicsparkradiant' },
  { id: 'r_morello', name: 'More More-ellonomicon', jaName: 'レディアント モレロノミコン', type: 'radiant', imgName: 'tft5_item_morellonomiconradiant' },
  { id: 'r_jeweled', name: 'Glamorous Gauntlet', jaName: 'レディアント ジュエル ガントレット', type: 'radiant', imgName: 'tft5_item_jeweledgauntletradiant' },
  { id: 'r_bluebuff', name: 'Blue Blessing', jaName: 'レディアント ブルーバフ', type: 'radiant', imgName: 'tft5_item_bluebuffradiant' },
  { id: 'r_vow', name: "Bulwark's Oath", jaName: 'レディアント プロテクターの誓い', type: 'radiant', imgName: 'tft5_item_frozenheartradiant' },
  { id: 'r_adaptive', name: 'Jaksho the Protean', jaName: 'レディアント アダプティブヘルム', type: 'radiant', imgName: 'tft5_item_adaptivehelmradiant' },
  { id: 'r_redemption', name: 'Absolution', jaName: 'レディアント スピリット ビサージュ', type: 'radiant', imgName: 'tft5_item_redemptionradiant' },
  { id: 'r_hoj', name: 'Fist of Fairness', jaName: 'レディアント ハンド オブ ジャスティス', type: 'radiant', imgName: 'tft5_item_handofjusticeradiant' },
  { id: 'r_bramble', name: 'Rosethorn Vest', jaName: 'レディアント ブランブルベスト', type: 'radiant', imgName: 'tft5_item_bramblevestradiant' },
  { id: 'r_gargoyle', name: 'Dvarapala Stoneplate', jaName: 'レディアント ガーゴイルストーンプレート', type: 'radiant', imgName: 'tft5_item_gargoylestoneplateradiant' },
  { id: 'r_sunfire', name: 'Sunlight Cape', jaName: 'レディアント サンファイアケープ', type: 'radiant', imgName: 'tft5_item_sunfirecaperadiant' },
  { id: 'r_steadfast', name: 'Legacy of the Colossus', jaName: 'レディアント 揺るがぬ心', type: 'radiant', imgName: 'tft5_item_nightharvesterradiant' },
  { id: 'r_dragon', name: "Dragon's Will", jaName: 'レディアント ドラゴン クロウ', type: 'radiant', imgName: 'tft5_item_dragonsclawradiant' },
  { id: 'r_evenshroud', name: 'Equinox', jaName: 'レディアント イーブンシュラウド', type: 'radiant', imgName: 'tft5_item_spectralgauntletradiant' },
  { id: 'r_quicksilver', name: 'Quickestsilver', jaName: 'レディアント クイックシルバー', type: 'radiant', imgName: 'tft5_item_quicksilverradiant' },
  { id: 'r_warmog', name: "Warmog's Pride", jaName: 'レディアント ワーモグ アーマー', type: 'radiant', imgName: 'tft5_item_warmogsarmorradiant' },
  { id: 'r_guardbreaker', name: 'Willbreaker', jaName: 'レディアント ストライカー フレイル', type: 'radiant', imgName: 'tft5_item_trapclawradiant' },
  { id: 'r_thiefs', name: "Rascal's sparringglovess", jaName: 'レディアント 盗賊のグローブ', type: 'radiant', imgName: 'tft5_item_thiefssparringglovessradiant' }
];
