/* ── 素材アイテム ── */
const ITEMS=[
  {id:'bf', name:'B.F. Sword', jaName:'B.F.ソード', type:'comp'}, 
  {id:'bow', name:'Recurve Bow', jaName:'リカーブボウ', type:'comp'},
  {id:'rod', name:'Needlessly Large Rod', jaName:'ムダニデカイロッド', type:'comp'}, 
  {id:'tear', name:'Tear of the Goddess', jaName:'女神の涙', type:'comp'},
  {id:'chain', name:'Chain Vest', jaName:'チェインベスト', type:'comp'}, 
  {id:'cloak', name:'Negatron Cloak', jaName:'ネガトロンクローク', type:'comp'},
  {id:'belt', name:"Giant's Belt", jaName:'ジャイアントベルト', type:'comp'}, 
  {id:'glove', name:'Sparring Gloves', jaName:'スパーリンググローブ', type:'comp'},
  {id:'spatula', name:'Spatula', jaName:'黄金のへら', type:'comp'},
  {id:'pan', name:'Frying Pan', jaName:'フライパン', type:'comp'}
];

/* ── サイオニック専用アイテム ── */
const PSIONIC_ITEMS = [
  { name: 'tft17_item_psyops_targetlockmod', jaName: 'ターゲットロック スコープ' },
  { name: 'tft17_item_psyops_sympatheticimplantmod', jaName: '共感インプラント' },
  { name: 'tft17_item_psyops_dronemod', jaName: 'ドローン アップリンク' },
  { name: 'tft17_item_psyops_chemicalcapacitormod', jaName: 'マルウェア マトリックス' },
  { name: 'tft17_item_psyops_grenademod', jaName: 'バイオ物質保存装置' }
];

/* ── 完成アイテムのレシピ ── */
const ITEM_RECIPES = {
  'bf_bf':{id:'deathblade', name:'Deathblade', jaName:'デスブレード'}, 
  'bf_bow':{id:'giantslayer', name:'Giant Slayer', jaName:'ジャイアントスレイヤー'},
  'bf_rod':{id:'hextech-gunblade', name:'Hextech Gunblade', jaName:'ヘクステックガンブレード'}, 
  'bf_tear':{id:'spear-of-shojin', name:'Spear of Shojin', jaName:'ショウジンの矛'},
  'bf_chain':{id:'edge-of-night', name:'Edge of Night', jaName:'ナイトエッジ'}, 
  'bf_cloak':{id:'bloodthirster', name:'Bloodthirster', jaName:'ブラッドサースター'},
  'bf_belt':{id:'steraks-gage', name:"Sterak's Gage", jaName:'ステラックの篭手'}, 
  'bf_glove':{id:'infinity-edge', name:'Infinity Edge', jaName:'インフィニティエッジ'},
  'bow_bow':{id:'red-buff', name:'Red Buff', jaName:'レッドバフ'}, 
  'bow_rod':{id:'guinsoos-rageblade', name:"Guinsoo's Rageblade", jaName:'グインソー レイジブレード'},
  'bow_tear':{id:'void-staff', name:'Void Staff', jaName:'ヴォイドスタッフ'}, 
  'bow_chain':{id:'titans-resolve', name:"Titan's Resolve", jaName:'巨人の誓い'},
  'bow_cloak':{id:'krakens-fury', name:"Kraken's Fury", jaName:'クラーケンの怒り'}, 
  'bow_belt':{id:'nashors-tooth', name:"Nashor's Tooth", jaName:'ナッシャー トゥース'},
  'bow_glove':{id:'last-whisper', name:'Last Whisper', jaName:'ラストウィスパー'},
  'rod_rod':{id:'rabadons-deathcap', name:"Rabadon's Deathcap", jaName:'ラバドンデスキャップ'}, 
  'rod_tear':{id:'archangels-staff', name:"Archangel's Staff", jaName:'アークエンジェルスタッフ'},
  'rod_chain':{id:'crownguard', name:'Crownguard', jaName:'クラウンガード'}, 
  'rod_cloak':{id:'ionic-spark', name:'Ionic Spark', jaName:'アイオニックスパーク'},
  'rod_belt':{id:'morellonomicon', name:'Morellonomicon', jaName:'モレロノミコン'}, 
  'rod_glove':{id:'jeweled-gauntlet', name:'Jeweled Gauntlet', jaName:'ジュエル ガントレット'},
  'tear_tear':{id:'blue-buff', name:'Blue Buff', jaName:'ブルーバフ'}, 
  'tear_chain':{id:'protectors-vow', name:"Protector's Vow", jaName:'プロテクターの誓い'},
  'tear_cloak':{id:'adaptive-helm', name:'Adaptive Helm', jaName:'アダプティブヘルム'}, 
  'tear_belt':{id:'spirit-visage', name:'Spirit Visage', jaName:'スピリット ビサージュ'},
  'tear_glove':{id:'hand-of-justice', name:'Hand of Justice', jaName:'ハンド オブ ジャスティス'},
  'chain_chain':{id:'bramble-vest', name:'Bramble Vest', jaName:'ブランブルベスト'}, 
  'chain_cloak':{id:'gargoyle-stoneplate', name:'Gargoyle Stoneplate', jaName:'ガーゴイルストーンプレート'},
  'chain_belt':{id:'sunfire-cape', name:'Sunfire Cape', jaName:'サンファイアケープ'}, 
  'chain_glove':{id:'steadfast-heart', name:'Steadfast Heart', jaName:'揺るがぬ心'},
  'cloak_cloak':{id:'dragons-claw', name:"Dragon's Claw", jaName:'ドラゴン クロウ'}, 
  'cloak_belt':{id:'evenshroud', name:'Evenshroud', jaName:'イーブンシュラウド'},
  'cloak_glove':{id:'quicksilver', name:'Quicksilver', jaName:'クイックシルバー'}, 
  'belt_belt':{id:'warmogs-armor', name:"Warmog's Armor", jaName:'ワーモグ アーマー'}, 
  'belt_glove':{id:'striker-flail', name:'Striker Flail', jaName:'ストライカー フレイル'}, 
  'glove_glove':{id:'thiefs-gloves', name:"Thief's Gloves", jaName:'盗賊のグローブ'},
  'spatula_bf':{id:'emblem_darkstar', name:'Dark Star Emblem', jaName:'ダークスターの紋章', grantedTrait: 'Dark Star'}, 
  'spatula_bow':{id:'emblem_timebreaker', name:'Timebreaker Emblem', jaName:'タイムブレイカーの紋章', grantedTrait: 'Timebreaker'},
  'spatula_rod':{id:'emblem_stargazer', name:'Stargazer Emblem', jaName:'星の観測者の紋章', grantedTrait: 'Stargazer'}, 
  'spatula_tear':{id:'emblem_spacegroove', name:'Space Groove Emblem', jaName:'スペースグルーヴの紋章', grantedTrait: 'Space Groove'},
  'spatula_chain':{id:'emblem_meeple', name:'Meeple Emblem', jaName:'ミィプルの紋章', grantedTrait: 'Meeple'}, 
  'spatula_cloak':{id:'emblem_arbiter', name:'Arbiter Emblem', jaName:'アービターの紋章', grantedTrait: 'Arbiter'},
  'spatula_belt':{id:'emblem_primordian', name:'Primordian Emblem', jaName:'プリモーディアンの紋章', grantedTrait: 'Primordian'}, 
  'spatula_glove':{id:'emblem_nova', name:'N.O.V.A. Emblem', jaName:'N.O.V.A.の紋章', grantedTrait: 'N.O.V.A.'},
  'spatula_spatula':{id:'tacticians-crown', name:"Tactician's Crown", jaName:'タクティシャンの王冠', teamSizeBonus: 1},
  'pan_bf':{id:'emblem_marauder', name:'Marauder Emblem', jaName:'略奪者の紋章', grantedTrait: 'Marauder'},
  'pan_bow':{id:'emblem_challenger', name:'Challenger Emblem', jaName:'チャレンジャーの紋章', grantedTrait: 'Challenger'},
  'pan_rod':{id:'emblem_voyager', name:'Voyager Emblem', jaName:'ボイジャーの紋章', grantedTrait: 'Voyager'},
  'pan_tear':{id:'emblem_shepherd', name:'Shepherd Emblem', jaName:'導き手の紋章', grantedTrait: 'Shepherd'},
  'pan_chain':{id:'emblem_bastion', name:'Bastion Emblem', jaName:'バスティオンの紋章', grantedTrait: 'Bastion'},
  'pan_cloak':{id:'emblem_vanguard', name:'Vanguard Emblem', jaName:'ヴァンガードの紋章', grantedTrait: 'Vanguard'},
  'pan_belt':{id:'emblem_brawler', name:'Brawler Emblem', jaName:'ブローラーの紋章', grantedTrait: 'Brawler'},
  'pan_glove':{id:'emblem_rogue', name:'Rogue Emblem', jaName:'ローグの紋章', grantedTrait: 'Rogue'},
  'unbuildable_anima': {id:'emblem_anima', name:'Anima Emblem', jaName:'アニマの紋章', grantedTrait: 'Anima'},
  'unbuildable_psionic': {id:'emblem_psionic', name:'Psionic Emblem', jaName:'サイオニックの紋章', grantedTrait: 'Psionic'},
  'unbuildable_sniper': {id:'emblem_sniper', name:'Sniper Emblem', jaName:'スナイパーの紋章', grantedTrait: 'Sniper'}
};

/* ── 消費アイテム ── */
const CONSUMABLES = {
  TINY_DUPE: { id: 'championduplicator_lesser', name: 'Tiny Champion Duplicator', jaName: '小さなチャンピオン複製機', type:'consumable' },
  LESSER_DUPE: { id: 'championduplicator_lesser', name: 'Lesser Champion Duplicator', jaName: '小型チャンピオン複製機', type:'consumable' },
  CHAMP_DUPE: { id: 'championduplicator', name: 'Champion Duplicator', jaName: 'チャンピオン複製機', type:'consumable' },
  REFORGER: { id: 'reforger', name: 'Reforger', jaName: '再合成装置', type:'consumable' },
  REMOVER: { id: 'remover', name: 'itemremover', jaName: '磁力式除去装置', type:'consumable' }
};

/* ── アーティファクト ── */
const ARTIFACTS = [
  { id: 'ahris-aura', name: "Ahri's Aura", jaName: 'アーリのオーラ', type: 'artifact', imgName: 'tft17_item_artifact_ahriartifact' },
  { id: 'evelynns-intuition', name: "Evelynn's Intuition", jaName: 'イブリンの直感', type: 'artifact', imgName: 'tft17_item_artifact_evelynnartifact' },
  { id: 'trinity-force', name: 'Trinity Force', jaName: 'インフィニティ フォース', type: 'artifact', imgName: 'tft4_item_ornninfinityforce' },
  { id: 'varuss-tenacity', name: "Varus's Tenacity", jaName: 'ヴァルスの執念', type: 'artifact', imgName: 'tft17_item_artifact_varusartifact' },
  { id: 'wits-end', name: "Wit's End", jaName: 'ウィッツ エンド', type: 'artifact', imgName: 'tft_item_artifact_witsend' },
  { id: 'void-gauntlet', name: 'Void Gauntlet', jaName: 'ヴォイド ガントレット', type: 'artifact', imgName: 'tft_item_artifact_voidgauntlet' },
  { id: 'ekkos-patience', name: "Ekko's Patience", jaName: 'エコーの忍耐', type: 'artifact', imgName: 'tft17_item_artifact_ekkoartifact' },
  { id: 'gamblers-blade', name: "Gambler's Blade", jaName: 'ギャンブラーの剣', type: 'artifact', imgName: 'tft7_item_shimmerscalegamblersblade' },
  { id: 'the-collector', name: 'The Collector', jaName: 'ゴールド コレクター', type: 'artifact', imgName: 'tft4_item_ornnthecollector' },
  { id: 'seekers-armguard', name: "Seeker's Armguard", jaName: 'シーカー アームガード', type: 'artifact', imgName: 'tft_item_artifact_seekersarmguard' },
  { id: 'silvermere-dawn', name: 'Silvermere Dawn', jaName: 'シルバーミアの夜明け', type: 'artifact', imgName: 'tft_item_artifact_silvermeredawn' },
  { id: 'statikk-shiv', name: 'Statikk Shiv Artifact', jaName: 'スタティック シヴ', type: 'artifact', imgName: 'tft_item_artifact_statikkshiv' },
  { id: 'snipers-focus', name: "Sniper's Focus", jaName: 'スナイパー フォーカス', type: 'artifact', imgName: 'tft9_item_ornnhorizonfocus' },
  { id: 'threshs-lantern', name: "Thresh's Lantern", jaName: 'スレッシュのランタン', type: 'artifact', imgName: 'tft17_item_artifact_threshlantern' },
  { id: 'zhonyas-paradox', name: "Zhonya's Paradox", jaName: 'ゾーニャの砂時計', type: 'artifact', imgName: 'tft4_item_ornnzhonyasparadox' },
  { id: 'sorakas-miracle', name: "Soraka's Miracle", jaName: 'ソラカの奇跡', type: 'artifact', imgName: 'tft17_item_artifact_sorakaartifact' },
  { id: 'titanic-hydra', name: 'Titanic Hydra', jaName: 'タイタン ハイドラ', type: 'artifact', imgName: 'tft_item_artifact_titanichydra' },
  { id: 'deaths-defiance', name: "Death's Defiance", jaName: 'デス ディファイアンス', type: 'artifact', imgName: 'tft4_item_ornndeathsdefiance' },
  { id: 'dawncore', name: 'Dawncore', jaName: 'ドーンコア', type: 'artifact', imgName: 'tft_item_artifact_dawncore' },
  { id: 'hullcrusher', name: 'Hullcrusher', jaName: 'ハルクラッシャー', type: 'artifact', imgName: 'tft9_item_ornnhullbreaker' },
  { id: 'fishbones', name: 'Fishbones', jaName: 'フィッシュボーン', type: 'artifact', imgName: 'tft_item_artifact_fishbones' },
  { id: 'flickerblade', name: 'Flickerblade', jaName: 'フリッカーブレード', type: 'artifact', imgName: 'tft_item_artifact_navoriflickerblades' },
  { id: 'prowlers-claw', name: "Prowler's Claw", jaName: 'プローラー クロウ', type: 'artifact', imgName: 'tft_item_artifact_prowlersclaw' },
  { id: 'mittens', name: 'Mittens', jaName: 'ミトン', type: 'artifact', imgName: 'tft_item_artifact_mittens' },
  { id: 'moguls-mail', name: "Mogul's Mail", jaName: 'モーグル メイル', type: 'artifact', imgName: 'tft7_item_shimmerscalemogulsmail' },
  { id: 'yasuos-bladework', name: "Yasuo's Bladework", jaName: 'ヤスオのブレードワーク', type: 'artifact', imgName: 'tft17_item_artifact_yasuoartifact' },
  { id: 'lightshield-crest', name: 'Lightshield Crest', jaName: 'ライトシールドのクレスト', type: 'artifact', imgName: 'tft_item_artifact_lightshieldcrest' },
  { id: 'rapid-firecannon', name: 'Rapid Firecannon Artifact', jaName: 'ラピッド ファイアキャノン', type: 'artifact', imgName: 'tft_item_artifact_rapidfirecannon' },
  { id: 'lich-bane', name: 'Lich Bane', jaName: 'リッチ ベイン', type: 'artifact', imgName: 'tft_item_artifact_lichbane' },
  { id: 'ludens-tempest', name: "Luden's Tempest", jaName: 'ルーデン テンペスト', type: 'artifact', imgName: 'tft_item_artifact_ludenstempest' },
  { id: 'unending-despair', name: 'Unending Despair', jaName: '不屈', type: 'artifact', imgName: 'tft_item_artifact_unendingdespair' },
  { id: 'everlasting-pact', name: 'Everlasting Pact', jaName: '不滅の協定', type: 'artifact', imgName: 'tft_item_artifact_eternalpact' },
  { id: 'dusks-blessing', name: "Dusk's Blessing", jaName: '夕闇の加護', type: 'artifact', imgName: 'tft_item_artifact_aegisofdusk' },
  { id: 'dawns-blessing', name: "Dawn's Blessing", jaName: '夜明けの加護', type: 'artifact', imgName: 'tft_item_artifact_aegisofdawn' },
  { id: 'hat-juice', name: 'Hat Juice', jaName: '帽子ジュース', type: 'artifact', imgName: 'tft_item_artifact_cappajuice' },
  { id: 'blighting-jewel', name: 'Blighting Jewel', jaName: '枯死の宝石', type: 'artifact', imgName: 'tft_item_artifact_blightingjewel' },
  { id: 'hellfire-hatchet', name: 'Hellfire Hatchet', jaName: '獄炎のハチェット', type: 'artifact', imgName: 'tft_item_artifact_hellfirehatchet' },
  { id: 'talisman-of-ascension', name: 'Talisman of Ascension', jaName: '超越のタリスマン', type: 'artifact', imgName: 'tft_item_artifact_talismanofascension' },
  { id: 'crown-of-demacia', name: 'Crown of Demacia', jaName: 'デマーシアの王冠', type: 'artifact', imgName: 'tft9_item_crownofdemacia' }
];

/* ── レディアントアイテム ── */
const RADIANT_ITEMS = [
  { id: 'r_deathblade', name: 'Luminous Deathblade', jaName: 'レディアント デスブレード', type: 'radiant', imgName: 'tft5_item_deathbladeradiant' },
  { id: 'r_giantslayer', name: 'Demonslayer', jaName: 'レディアント ジャイアントスレイヤー', type: 'radiant', imgName: 'tft5_item_giantslayerradiant' },
  { id: 'r_hextech-gunblade', name: 'Hextech Lifeblade', jaName: 'レディアント ヘクステックガンブレード', type: 'radiant', imgName: 'tft5_item_hextechgunbladeradiant' },
  { id: 'r_spear-of-shojin', name: 'Spear of Hirana', jaName: 'レディアント ショウジンの矛', type: 'radiant', imgName: 'tft5_item_spearofshojinradiant' },
  { id: 'r_edge-of-night', name: 'Brink of Dawn', jaName: 'レディアント ナイトエッジ', type: 'radiant', imgName: 'tft5_item_guardianangelradiant' },
  { id: 'r_bloodthirster', name: 'Blessed Bloodthirster', jaName: 'レディアント ブラッドサースター', type: 'radiant', imgName: 'tft5_item_bloodthirsterradiant' },
  { id: 'r_steraks-gage', name: "Sterak's Megashield", jaName: 'レディアント ステラックの篭手', type: 'radiant', imgName: 'tft5_item_steraksgageradiant' },
  { id: 'r_infinity-edge', name: 'Zenith Edge', jaName: 'レディアント インフィニティエッジ', type: 'radiant', imgName: 'tft5_item_infinityedgeradiant' },
  { id: 'r_red-buff', name: 'Crest of Cinders', jaName: 'レディアント レッドバフ', type: 'radiant', imgName: 'tft5_item_rapidfirecannonradiant' }, 
  { id: 'r_guinsoos-rageblade', name: "Guinsoo's Reckoning", jaName: 'レディアント グインソー レイジブレード', type: 'radiant', imgName: 'tft5_item_guinsoosragebladeradiant' },
  { id: 'r_void-staff', name: "Statikk's Favor", jaName: 'レディアント ヴォイドスタッフ', type: 'radiant', imgName: 'tft5_item_statikkshivradiant' },
  { id: 'r_titans-resolve', name: "Titan's Vow", jaName: 'レディアント 巨人の誓い', type: 'radiant', imgName: 'tft5_item_titansresolveradiant' },
  { id: 'r_krakens-fury', name: "Runaan's Tempest", jaName: 'レディアント クラーケンの怒り', type: 'radiant', imgName: 'tft5_item_runaanshurricaneradiant' },
  { id: 'r_nashors-tooth', name: "Baron's Gift", jaName: 'レディアント ナッシャー トゥース', type: 'radiant', imgName: 'tft5_item_leviathanradiant' },
  { id: 'r_last-whisper', name: 'Eternal Whisper', jaName: 'レディアント ラストウィスパー', type: 'radiant', imgName: 'tft5_item_lastwhisperradiant' },
  { id: 'r_rabadons-deathcap', name: "Rabadon's Ascended Deathcap", jaName: 'レディアント ラバドンデスキャップ', type: 'radiant', imgName: 'tft5_item_rabadonsdeathcapradiant' },
  { id: 'r_archangels-staff', name: "Urf-Angel's Staff", jaName: 'レディアント アークエンジェルスタッフ', type: 'radiant', imgName: 'tft5_item_archangelsstaffradiant' },
  { id: 'r_crownguard', name: 'Royal Crownshield', jaName: 'レディアント クラウンガード', type: 'radiant', imgName: 'tft5_item_crownguardradiant' },
  { id: 'r_ionic-spark', name: 'Covalent Spark', jaName: 'レディアント アイオニックスパーク', type: 'radiant', imgName: 'tft5_item_ionicsparkradiant' },
  { id: 'r_morello', name: 'More More-ellonomicon', jaName: 'レディアント モレロノミコン', type: 'radiant', imgName: 'tft5_item_morellonomiconradiant' },
  { id: 'r_jeweled-gauntlet', name: 'Glamorous Gauntlet', jaName: 'レディアント ジュエル ガントレット', type: 'radiant', imgName: 'tft5_item_jeweledgauntletradiant' },
  { id: 'r_blue-buff', name: 'Blue Blessing', jaName: 'レディアント ブルーバフ', type: 'radiant', imgName: 'tft5_item_bluebuffradiant' },
  { id: 'r_protectors-vow', name: "Bulwark's Oath", jaName: 'レディアント プロテクターの誓い', type: 'radiant', imgName: 'tft5_item_frozenheartradiant' },
  { id: 'r_adaptive-helm', name: 'Jaksho the Protean', jaName: 'レディアント アダプティブヘルム', type: 'radiant', imgName: 'tft5_item_adaptivehelmradiant' },
  { id: 'r_spirit-visage', name: 'Absolution', jaName: 'レディアント スピリット ビサージュ', type: 'radiant', imgName: 'tft5_item_redemptionradiant' },
  { id: 'r_hand-of-justice', name: 'Fist of Fairness', jaName: 'レディアント ハンド オブ ジャスティス', type: 'radiant', imgName: 'tft5_item_handofjusticeradiant' },
  { id: 'r_bramble-vest', name: 'Rosethorn Vest', jaName: 'レディアント ブランブルベスト', type: 'radiant', imgName: 'tft5_item_bramblevestradiant' },
  { id: 'r_gargoyle-stoneplate', name: 'Dvarapala Stoneplate', jaName: 'レディアント ガーゴイルストーンプレート', type: 'radiant', imgName: 'tft5_item_gargoylestoneplateradiant' },
  { id: 'r_sunfire-cape', name: 'Sunlight Cape', jaName: 'レディアント サンファイアケープ', type: 'radiant', imgName: 'tft5_item_sunfirecaperadiant' },
  { id: 'r_steadfast-heart', name: 'Legacy of the Colossus', jaName: 'レディアント 揺るがぬ心', type: 'radiant', imgName: 'tft5_item_nightharvesterradiant' },
  { id: 'r_dragons-claw', name: "Dragon's Will", jaName: 'レディアント ドラゴン クロウ', type: 'radiant', imgName: 'tft5_item_dragonsclawradiant' },
  { id: 'r_evenshroud', name: 'Equinox', jaName: 'レディアント イーブンシュラウド', type: 'radiant', imgName: 'tft5_item_spectralgauntletradiant' },
  { id: 'r_quicksilver', name: 'Quickestsilver', jaName: 'レディアント クイックシルバー', type: 'radiant', imgName: 'tft5_item_quicksilverradiant' },
  { id: 'r_warmogs-armor', name: "Warmog's Pride", jaName: 'レディアント ワーモグ アーマー', type: 'radiant', imgName: 'tft5_item_warmogsarmorradiant' },
  { id: 'r_striker-flail', name: 'Willbreaker', jaName: 'レディアント ストライカー フレイル', type: 'radiant', imgName: 'tft5_item_trapclawradiant' },
  { id: 'r_thiefs-gloves', name: "Rascal's Gloves", jaName: 'レディアント 盗賊のグローブ', type: 'radiant', imgName: 'tft5_item_thiefsglovesradiant' }
];
